# Generated by Django 4.2.17 on 2025-01-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_alter_merchant_options_merchant_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='merchants', to='merchants.category'),
        ),
    ]
