# Generated by Django 4.2.17 on 2025-01-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_midtrans_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
